export type EventType =
  | 'ORDER_CANCELLATION_REQUESTED'
  | 'CREATED'
  | 'CONFIRMED'
  | 'DISPATCHED'
  | 'READY_FOR_PICKUP'
  | 'PICKUP_AREA_ASSIGNED'
  | 'DELIVERED'
  | 'CONCLUDED'
  | 'CANCELLATION_REQUESTED'
  | 'CANCELLATION_REQUEST_DENIED'
  | 'CANCELLED';

export interface OrderBaseEvent {
  /**
   * A unique identifier of the event.
   */
  eventId: string;

  /**
   * The event type
   */
  eventType: EventType;

  /**
   * 	The unique identifier of the order. The order ID is generated by the Ordering Application.
   */
  orderId: string;

  /**
   * The URL to get the order details
   */
  orderURL: string;
  /**
   * This field must be filled in with the AppId of the Ordering Application that originated the order. This field is to help the applications that will work as a Hub, intermediating the requests from the Ordering Application with the Software Service.
   */
  sourceAppId?: string;
}
