import { Merchant } from '..';

/**
 * Get specific merchant info reading status provided by the Ordering Application.
 * GET /v1/merchantStatus?merchantId=
 * Query parameters
 * merchantId
 * Unique Identifier. Identifies the merchant in the different systems that the merchant will communicate.
 * This id must be generated by the merchant's Software Service.
 * To avoid duplicates between different merchants it is recommended that the software creates the merchantId using:
 * Merchant Document + UUID
 * If this is not possible, it is recommended to at least use a UUID.
 */
export interface GetMerchantStatusResponse {
  /**
   * Date of last attempt to read merchant information.
   */
  lastRead: string;

  /**
   * Reading attempt status
   */
  status: 'SUCCESS' | 'PROCESSING' | 'FAIL';

  /**
   * Open field to provide any relevant information to the caller. Eg: Error messages or causes.
   */
  moreInfo?: string;
}

export interface GetMerchantResponse extends Merchant {
  /**
   * The last modified date and time.
   * This should be used in conjuction of the TTL field to update the information on the ordering aplication.
   * (UTC date-time in ISO timestamp format).
   */
  lastUpdate: string;

  /**
   * Time to Live (in seconds). Min: 500 Max: 86400. A new request must be done when the TTL expires.*/
  TTL: string;
}
